[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 1
auto_detect_solc = false
solc_version = "0.8.15"
evm_version = "london"
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

unknown_chain = { key = "", chain = 1, url = "https://virtual.mainnet.rpc.tenderly.co/a8d6ee80-8564-43f0-8af6-da8dc37b3264" }
